config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :document

  resources :news
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
end

app/models/news.rb
class News < ApplicationRecord

  validates :judul, presence: true,
            length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/document_controller.rb
class DocumentController < ApplicationController

  def index
    @document = Document.all
  end

  def create
@document = Document
  end

  def new

  end

  def edit

  end

  def show

  end

  def update

  end

  def destroy
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @besok = Date.tomorrow
    @bulan_depan = Date.today + 30.days
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController

  def index
    @news = News.all
  end

  def new
    @news = News.new
  end

  def create
    @news = News.new(news_params)

    if @news.save
      redirect_to @news
    else
      render 'new'
    end
  end

  def show
    @news = News.find(params[:id])

  end

  private
  def news_params
    params.require(:news).permit(:judul, :isi, :penulis)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/document_helper.rb
module DocumentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/document/index.html.erb
test

app/views/document/new.html.erb
<h1></h1>

app/views/home/index.html.erb
<h2>Hallo World!</h2>
<p>
  The Time is now: <%= Time.now %>
  <br>
  The time for tomorrow will be <%= @besok %>

  <br>

  <%= link_to 'Daftar Berita', controller: 'news' %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/news/index.html.erb
<h1>Listing News</h1>

<%= link_to 'Tambah Berita', new_news_path %>


<table>
  <tr>
    <th>Judul</th>
    <th>Isi</th>
    <th>Penulis</th>
  </tr>

  <% @news.each do |news| %>
      <tr>
        <td><%= news.judul %></td>
        <td><%= news.isi %></td>
        <td><%= news.penulis %></td>
        <td><%= link_to 'Show', news_path(news) %></td>
      </tr>
  <% end %>
</table>

app/views/news/new.html.erb
<%= form_for :news, url: news_index_path do |f| %>

    <% if @news.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@news.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @news.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :judul %><br>
      <%= f.text_field :judul %>
    </p>

    <p>
      <%= f.label :isi %><br>
      <%= f.text_area :isi %>
    </p>

    <p>
      <%= f.label :penulis %><br>
      <%= f.text_field :penulis %>
    </p>

    <p>
      <%= f.submit "Simpan Berita"%>
    </p>
<% end %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<p>
  <strong>Judul:</strong>
  <%= @news.judul %>
</p>

<p>
  <strong>Isi:</strong>
  <%= @news.isi %>
</p>

<p>
  <strong>Penulis:</strong>
  <%= @news.penulis %>
</p>